language: node_js
node_js:
  - "16"
  - "14"
  - "12"
  - "10"

cache:
  directories:
    - node_modules

before_script:
  - npm uninstall typescript --no-save
  - npm uninstall tslint --no-save
  - npm install

script:
  - npm run test

after_success:
  - npm run coverage

branches:
  only:
    - main
    - dev